task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ubuntu:20.04
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - apt update
       - apt install sudo
       - DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
       - ln -sf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime
       - apt-get install -y tzdata
       - dpkg-reconfigure --frontend noninteractive tzdata
       - sudo apt update -y && sudo apt install git aria2 curl wget rsync zip unzip lzma cpio ccache clang -y
       - sudo apt install python3 -y
       - sudo ln -sf /usr/bin/python3 /usr/bin/python
       - git config --global user.name "Sushrut1101"
       - git config --global user.email "guptasushrut@gmail.com"
       
       - cd ~
  
  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Syn_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - sudo apt-get install bc -y
      - sudo apt-get install bison -y
      - sudo apt-get install build-essential -y
      - sudo apt-get install curl -y
      - sudo apt-get install flex -y
      - sudo apt-get install g++-multilib -y
      - sudo apt-get install gcc-multilib -y
      - sudo apt-get install git -y
      - sudo apt-get install gnupg -y
      - sudo apt-get install gperf -y
      - sudo apt-get install libxml2 -y
      - sudo apt-get install liblz4-tool -y
      - sudo apt-get install libncurses5-dev -y
      - sudo apt-get install libsdl1.2-dev -y
      - sudo apt-get install imagemagick -y
      - sudo apt-get install lunzip -y
      - sudo apt-get install lzop -y
      - sudo apt-get install schedtool -y
      - sudo apt-get install squashfs-tools -y
      - sudo apt-get install xsltproc -y
      - sudo apt-get install zip -y
    
      - sudo apt-get install python -y
      - sudo apt-get install xmlstarlet -y
      - sudo apt-get install virtualenv -y
      - sudo apt-get install xz-utils -y 
      - sudo apt-get install rr -y
      - sudo apt-get install jq -y
      - sudo apt-get install libncurses5 -y
      - sudo apt-get install pngcrush -y
      - sudo apt-get install lib32ncurses5-dev -y
      - sudo apt-get install git-lfs -y
      - sudo apt-get install openjdk-11-jdk-headless -y
      
      - sudo apt-get update
      - sudo apt-get install default-jdk -y
      
      - export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64

      - echo $JAVA_HOME

      - echo "export JAVA_HOME=/usr/lib/jvm/java-1.11.0-openjdk-amd64" >> ~/.bashrc

      - source ~/.bashrc

      - sudo apt-get install curl -y
      - mkdir -p ~/bin
      - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      - chmod a+x ~/bin/repo 
      - PATH="$HOME/bin:$PATH"
      - source ~/.profile 
  

      - export USE_CCACHE=1
      - export CCACHE_COMPRESS=1
      - export CCACHE_MAXSIZE=50G # 50 GB
      
   
      
      - mkdir -p ~/lineage-20-build-gsi
      - cd ~/lineage-20-build-gsi
      - repo init -u https://github.com/LineageOS/android.git -b lineage-20.0
      - git clone https://github.com/AndyCGYan/lineage_build_unified lineage_build_unified -b lineage-20-light
      - git clone https://github.com/AndyCGYan/lineage_patches_unified lineage_patches_unified -b lineage-20-light

      - cd ~
      
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================".  
      - cd ~/lineage-20-build-gsi
      - $EXTRA_CMD
       
      - . lineage_build_unified/buildbot_unified.sh treble 64VN 64VS 64GN
      
